app/blueprints/__init__.py
from .home import home_page
from .recommend import recommend_api

app/blueprints/home/__init__.py
from .blueprint import home_page

app/blueprints/home/blueprint.py
"""
This module is the Flask blueprint for the product catalog page (/).
"""


from flask import Blueprint, render_template

home_page = Blueprint('home_page', __name__)


@home_page.route('/')
# @auth_optional
def hello():
    
    return render_template('landing.html')


@home_page.route('/hello')
# @auth_optional
def display():
    
    return render_template('home.html',) 
                      

app/blueprints/recommend/__init__.py
from .blueprint import recommend_api

app/blueprints/recommend/blueprint.py
from flask import Blueprint, render_template, jsonify, request, redirect
import tensorflow as tf
from tensorflow.keras.models import Model

import numpy as np
import pandas as pd

recommend_api = Blueprint('recommend', __name__)

user_embedding = None
product_embedding = None
skin_average_embedding = None
model = None
products = pd.read_csv('static/feature_embeddings/products.csv')

USER_EMBEDDING = 'user_embedding.npy'
PRODUCT_EMBEDDING = 'product_embedding.npy'
USER_EMBEDDING_DL = 'user_embedding_dl.npy'
PRODUCT_EMBEDDING_DL = 'product_embedding_dl.npy'
SKIN_EMBEDDING = 'skin_average_embedding.npy'
DOT = 'dot'
COSINE = 'cosine'
MODEL = 'my_model.h5'

sktypes = ['normal', 'combination', 'dry', 'oily']
sktones = ['light', 'deep', 'olive', 'fair', 'medium', 'dark']

def load_embeddings():
   global user_embedding, product_embedding, skin_average_embedding

   user_embedding = np.load("static/feature_embeddings/" + USER_EMBEDDING, allow_pickle=True)
   product_embedding = np.load("static/feature_embeddings/" + PRODUCT_EMBEDDING, allow_pickle=True)
   skin_average_embedding = np.load("static/feature_embeddings/" + SKIN_EMBEDDING, allow_pickle=True)

def load_model():
   global model

   model = tf.keras.models.load_model('/static/models/' + MODEL)

   layer_name = 'embedding_4'
   model = Model(inputs=model.input, outputs=model.get_layer(layer_name).output)


def compute_scores(query_embedding, item_embeddings, measure=DOT):
   u = query_embedding
   V = item_embeddings
   if measure == COSINE:
      V = V / np.linalg.norm(V, axis=1, keepdims=True)
      u = u / np.linalg.norm(u)
   scores = u.dot(V.T)
   return scores

def user_recommendations(user_id, user_embedding, product_embedding, measure=DOT, exclude_rated=True, k=6):
   scores = compute_scores(
      user_embedding[user_id], product_embedding, measure)
   score_key = measure + ' score'
   
   df = pd.DataFrame({
      score_key: list(scores),
      'product_id': products['product_id'],
      'title': products['title'],
      'category': products['category'],
   })
   if exclude_rated:
      # remove products that are already rated
      rated_products = ratings[ratings.user_id == user_id]["product_id"].values
      df = df[df.product_id.apply(lambda product_id: product_id not in rated_products)]
   
   return df.values.tolist()

def new_user_recommendations(user_embedding, product_embedding, measure=DOT, k=5):
   scores = compute_scores(
      user_embedding, product_embedding, measure)
   score_key = measure + ' score'
   
   df = pd.DataFrame({
      score_key: list(scores),
      'product_id': products['product_id'],
      'title': products['title'],
      'category': products['category'],
      'image_url': products['image_url']
   })
   
   return df.sort_values([score_key], ascending=False).head(k)

def product_neighbors(product_embedding, title_substring, measure=DOT, k=6):
   # Search for product ids that match the given substring.
   ids =  products[products['title'].str.contains(title_substring)].index.values
   titles = products.iloc[ids]['title'].values
   
   if len(titles) == 0:
      raise ValueError("Found no products with title %s" % title_substring)
   print("Nearest neighbors of : %s." % titles[0])
   if len(titles) > 1:
      print("[Found more than one matching product. Other candidates: {}]".format(
         ", ".join(titles[1:])))
   product_id = ids[0]
   scores = compute_scores(
      product_embedding[product_id], product_embedding,
      measure)
   score_key = measure + ' score'
   df = pd.DataFrame({
      score_key: list(scores),
      'title': products['title'],
      'category': products['category']
   })
   
   return df.values.tolist()

@recommend_api.route('/recommend', methods=['GET', 'POST'])  
def compute_recommendation():

   if user_embedding is None or product_embedding is None or skin_average_embedding is None:
      load_embeddings()

   if request.method == 'GET':
      return redirect("/")

   if request.method == 'POST':
      
      # data = request.form

      skin_type = request.form['options_skin_type']
      skin_tone = request.form['options_skin_tone']

      user_profile = {'skin_type' : skin_type, 'skin_tone': skin_tone}

      # calculate feature vectors of user from input data
      index = len(sktones) * sktypes.index(skin_type) + sktones.index(skin_tone)
      feature_vector = skin_average_embedding[index]

      # recommendation
      df = new_user_recommendations(feature_vector, product_embedding, measure='COSINE', k=10)
      headers = list(df)

      products = []

      for index, row in df.iterrows():
         obj = {}

         for idx, item in enumerate(row):
            obj[headers[idx]] = item
         
         products.append(obj)

   return render_template('recommend.html', user_profile=user_profile, products=products, tables=[df.to_html(classes='data')], titles=df.columns.values)

app/main.py
import firebase_admin
from flask import Flask

from blueprints import *


# Initialize Firebase Admin SDK.
# See https://firebase.google.com/docs/admin/setup for more information.
firebase = firebase_admin.initialize_app()

app = Flask(__name__)
app.secret_key = b'A Super Secret Key'


app.register_blueprint(home_page)
app.register_blueprint(recommend_api)



if __name__ == '__main__':
    app.run(debug=True)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Skincare Therapy</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta content="" name="keywords">
  <meta content="" name="description">
  
  <link href="img/favicon.png" rel="icon">
  <link href="img/apple-touch-icon.png" rel="apple-touch-icon">
  <link rel="stylesheet" href="static/css/bulma.min.css">
  <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Poppins:300,400,500,700" rel="stylesheet">
  <link href="static/css/style.css" rel="stylesheet">
</head>

<body>                                  
  <nav class="navbar has-background-black">                                                    
    <div class="navbar-menu">
      <div class="navbar-start">
        <a class="navbar-item has-text-light" href="/">Skincare Recommendation</a>
      </div>
    </div>
  </nav>

  {% block content %}{% endblock %}

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://www.gstatic.com/firebasejs/5.7.0/firebase.js"></script>
  <script src="/static/js/initFirebase.js"></script>
  <script src="/static/js/signInOutWithGoogle.js"></script>
  <script src="/static/js/main.js"></script>
</body>
</html>

app/templates/home.html
{% extends "base.html" %}
{% block content %}
  <section id="hero" class="home">
      <div class="hero-container">
          <div class="container">
            <h1>Welcome to Skin Therapy </h1>
            <h2>Our recommendation system will assist you to choose your best skincare products</h2>
          </div>

          <div class="container form-profile">
              <div class="container">
                <section class="get-profile">
                  <form action="/recommend" name="form-get-profile" method="POST">
                    <div class="profile-section">
                      <h3 class="form-title">Choose Your Skin Type</h3>
                      <div class="list-options">
                          <label><input type="radio" name="options_skin_type" value="normal"> Normal</label>
                        <label><input type="radio" name="options_skin_type" value="dry"> Dry</label>
                        <label><input type="radio" name="options_skin_type" value="combination"> Combination</label>
                        <label><input type="radio" name="options_skin_type" value="oily"> Oily </input></label>
                      </div>
                    </div>
                    
                    <div class="profile-section">
                      <h3 class="form-title">Choose Your Skin Tone</h3>
                      <div class="list-options">
                          <label><input type="radio" name="options_skin_tone" value="light"> Light</label>
                          <label><input type="radio" name="options_skin_tone" value="deep"> Deep</label>
                          <label><input type="radio" name="options_skin_tone" value="olive"> Olive</label>
                          <label><input type="radio" name="options_skin_tone" value="fair"> Fair</label>
                          <label><input type="radio" name="options_skin_tone" value="medium"> Medium</label>
                          <label><input type="radio" name="options_skin_tone" value="dark"> Dark</label>
                          
                      </div>
                    </div>
            
                    <button type="submit">Submit</button>
                  </form>
                </section>
              </div>
          </div>
      </div>
  </section>
{% endblock %}

app/templates/landing.html
{% extends "base.html" %}
{% block content %}
    <section id="hero" class="home">
      <div class="hero-container">
          <div class="container">
            <h1>Welcome to Skin Therapy </h1>
            <h2>Our recommendation system will assist you to choose your best skincare products</h2> 
            <a href="{{ url_for('home_page.display') }}" style = "background-color: white; border-radius: 100px; margin: 10px; padding: 14px; font-size: 16px"> Get Started</a>
          </div>
      </div>
    </section>  

{% endblock %}

app/templates/recommend.html
{% extends "base.html" %}
{% block content %}
  <section id="hero" class="section-recommend">
    <div class="hero-container">
      <div class="container">
          <a href="/">BACK TO HOME</a>
          <h1>Here are what we recommend to you:</h1>
      </div>

      <div class="container your-profile">
        <h2 class="title">Your skin profile:</h2>
        <p>Skin type: {{ user_profile.skin_type }}</p>
        <p>Skin tone: {{ user_profile.skin_tone }}</p>
      </div>
      <div class="container recommended-products">
        <div class="tile is-ancestor">
          {% for column in [0, 1, 2, 3]%}
          <div class="tile is-parent is-3 is-vertical">
            <div class="tile is-child">
              {% for product in products[column::4] %}
                <div class="card">
                    <div class="card-image">
                      <figure class="image is-4by3">                        
                        {% set image_url = 'https://bulma.io/images/placeholders/1280x960.png' %}
                        {% if product.image_url!='Not Found' %}
                          {% set image_url = product.image_url %}
                        {% endif %}
                        <img src="{{ image_url }}" alt="Placeholder image">
                      </figure>
                    </div>
                    <div class="card-content">
                      <div class="media">
                        <div class="media-content">
                          <p class="title is-4">{{ product.title }}</p>
                          <p class="subtitle is-6">{{ product.category }}</p>
                        </div>
                      </div>
                    </div>
                  </div>
              {% endfor %}
            </div>
          </div>
          {% endfor %}
        </div>
    </div>
  </section>
  
  
{% endblock %}